### ISSUE TITLE
Add exportConfiguration endpoint

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eonapi#1]
The exportConfiguration is available for each add or delete action, but not globally.

So, if you want to add multiple hosts, you have to:
- add N-1 hosts without export
- add the last host with export

Adding exportConfiguration will make automation easier (i.e. all hosts would be added in the same way).

**Comment by EyesOfNetwork** [comment]
Add exportConfiguration fonction !!!
