### ISSUE TITLE
createHost : HTTP error 500

### ISSUE THREAD

**Issue by IPv777** [EyesOfNetworkCommunity/eonapi#11]
Hello

when I want to add a host with createHost, I get an error 500
from the framework "Slim".

My API key is valid :+1: 
`GET https://192.168.7.2/eonapi/getAuthenticationStatus?username=admin&apiKey=myapikey`

`{
    "api_version": "2.4.2",
    "http_code": "200 OK",
    "status": "authorized"
}`

My request : 
`POST https://192.168.7.2/eonapi/createHost?username=admin&apiKey=myapikey&templateHostName=GENERIC_HOST&hostName=TestHS&hostIp=8.8.8.8&hostAlias=My+first+host&contactName=admin&contactGroupName=admins&exportConfiguration=true`

and the response as error 500 :
![image](https://user-images.githubusercontent.com/19636346/71185601-0b5aa380-227c-11ea-9675-cac40a473915.png)

Thanks :)

**Comment by davoult** [comment]
@jeremyHoarau idea?

**Comment by jeremyHoarau** [comment]
Hello,
You have to pass those arguments through the request body as a json file like this : 

- **your url :** https://192.168.7.2/eonapi/createHost?username=admin&apiKey

- **The request body :**  

```
{
	"templateHostName": "GENERIC_HOST",
	"hostName": "TestHS",
	"hostIp": "8.8.8.8",
	"hostAlias": "My first host",
	"contactName": "admin",
	"contactGroupName": "admins",
	"exportConfiguration": true
}
```
Here a curl command to test this request : 
```
curl --insecure -XPOST -H "Content-type: application/json" -d '{
	"templateHostName": "GENERIC_HOST",
	"hostName": "TestHS",
	"hostIp": "8.8.8.8",
	"hostAlias": "My first host",
	"contactName": "admin",
	"contactGroupName": "admins",
	"exportConfiguration": true
}' 'https://192.168.7.2/eonapi/createHost?username=admin&apiKey'
```
Does this solve your problems?

**Comment by IPv777** [comment]
my request was not good, it's okay, thanks :)
another thing : could you say me if it's possible to add a Host to a HostGroup with this API ? I don't find the endpoint :/

**Comment by jeremyHoarau** [comment]
No problem ;) 
Indeed, it seems that we have not fully updated our documentation yet, sorry for that. You have this function in the API :  " _addHostGroupToHost( $hostGroupName, $hostName, $exportConfiguration = FALSE )_" which should satisfy your needs.
