### ISSUE TITLE
Liens pour les docs EoN : HS

### ISSUE THREAD

**Issue by IPv777** [EyesOfNetworkCommunity/eonapi#13]
Bonjour,
petite issue qui ne concerne pas l'API mais je la place ici dans l'espoir qu'elle soit lue...

depuis la refonte de votre site web courant décembre (à l'occasion de la sortie de la v5.3), il est impossible d'accéder aux documentations EoN, et c'est assez problématique :S 
Si j'ai bien isolé le problème : les docs sur l'ancien site étaient accessibles depuis le répertoire https://www.eyesofnetwork.com/eonrepo/

@jeremyHoarau pourrais-tu transmettre ce problème aux personnes en charge du site ?

Merci par avance 😍 
Guillaume

**Comment by davoult** [comment]
Bonjour,
La documentation est de nouveau disponible en téléchargement:
[EyesOfNetwork-documentations-v5.zip](https://www.eyesofnetwork.com/files/EyesOfNetwork-documentations-v5.zip )

Sébastien,
