### ISSUE TITLE
Manage Host Parent/Child relationship

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eonapi#6]
Hi,

it could be useful to manage host parent/child relationship with the API, when adding/modifying hosts.

**Comment by IPv777** [comment]
Hello :)

To start this comment : happy new year !
Then, I'm asking for some news about this endpoint, is it on the road ?
We are using EoN but we've ~150 Hosts to import in the software, so I'm trying to use this API by creating a Python snippet.
We would like to create Hosts `createHost()`, add them into HostGroups `addHostGroupToHost()`, setup HostTemplate `addHostTemplateToHost()` ...... and setup network hierarchy `addParentToHost() ??`

Have a good day :)

**Comment by jeremyHoarau** [comment]
Happy new year !

To celebrate this new year I have created a new branch called kinship [https://github.com/EyesOfNetworkCommunity/eonapi/tree/kinship](url) wich I hope will fulfill your need. ;)  

Two new functions `addParentToHost` and `deleteParentToHost` have been added to the API wich allow you to manage hosts hierarchys in  a simple way. Those two functions are use through a post request with two parameters required in the json sended like the example below : 
`{
  "childName": "srv_2020",
  "parentName":"srv_2019"
  
}`

Have a good day !

**Comment by IPv777** [comment]
Perfect, it's working fine :D 
A big thanks ;)

**Comment by jeremyHoarau** [comment]
No problem ;)
