### ISSUE TITLE
Error 404 with Slim framework and security issue ?

### ISSUE THREAD

**Issue by ChamMach** [EyesOfNetworkCommunity/eonapi#9]
Hello there,

1. On a fresh server (EON 5.2), I use an Ansible script which I use a function of the api (getHost) and I have this message : 

404 Page Not Found</h1><p>The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.</p><a href=\"/eonapi/\">

More details : 
![image](https://user-images.githubusercontent.com/23166349/64997123-164e1280-d8e0-11e9-8727-de10ef00209e.png)

I checked a lot of things (.htaccess/httpd configuration ...) but I don't really know Slim so maybe it's one of the "route" or composer ? I don't know, but on one of my other server I don't have this error and it's work like a charm (I didn't install it so I can't reproduce the same installation/configuration). 

Can you help me ?

2. In addition, when I tested the API, I found that the API keys are the same regardless of the EON and the environment in which the APIs are installed. So, there is no way to have a "unique" key even if we use the same login / password on 2 different EON ?

Thank you in advance.

Regards,

Cham

**Comment by davoult** [comment]
Using **POST** HTTP request?

**Comment by ChamMach** [comment]
Hi,

I already use a POST HTTP request

**Comment by ChamMach** [comment]
Solved:

1. Without paying attention, I added a symbolic link in the _eonapi_ folder.

2. I was wrong, everything is good!

Thanks: D
